# Generated by Django 3.2.8 on 2021-11-09 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudiante_Lecciones',
        ),
    ]
