# Generated by Django 3.2.8 on 2021-11-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCatalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='orden',
            field=models.SmallIntegerField(verbose_name='Orden de aparición'),
        ),
    ]
