# Generated by Django 3.2.8 on 2021-11-09 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_estudiante_lecciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LearningCatalog', '0002_alter_archivo_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.usermodel'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Estudiante_Lecciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.estudiante')),
                ('leccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LearningCatalog.leccion')),
            ],
        ),
    ]
