# Generated by Django 3.2.8 on 2021-11-09 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LearningCatalog', '0003_auto_20211108_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
